# Generated by Django 2.2.1 on 2020-07-07 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='att_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='subscriptions.ATTSubscription'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='sprint_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='subscriptions.SprintSubscription'),
        ),
    ]
