# Generated by Django 2.2.1 on 2020-07-20 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datausagerecord',
            name='att_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='subscriptions.ATTSubscription'),
        ),
        migrations.AlterField(
            model_name='datausagerecord',
            name='kilobytes_used',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datausagerecord',
            name='sprint_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='subscriptions.SprintSubscription'),
        ),
        migrations.AlterField(
            model_name='datausagerecord',
            name='usage_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voiceusagerecord',
            name='att_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='subscriptions.ATTSubscription'),
        ),
        migrations.AlterField(
            model_name='voiceusagerecord',
            name='seconds_used',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voiceusagerecord',
            name='sprint_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='subscriptions.SprintSubscription'),
        ),
        migrations.AlterField(
            model_name='voiceusagerecord',
            name='usage_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AggregateVoiceUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('aggregated_price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('aggregated_seconds_used', models.IntegerField(blank=True, null=True)),
                ('voice_records', models.ManyToManyField(to='usage.VoiceUsageRecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AggregateDataUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('aggregated_price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('aggregated_kilobytes_used', models.IntegerField(blank=True, null=True)),
                ('data_records', models.ManyToManyField(to='usage.DataUsageRecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
